project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  title: "Ata Bioinfo"
  sidebar:
    style: "docked"
    search: true
    left:
    contents: 
      - section: "Nextflow"
        contents:
        - posts/nextflow_posts/digram.qmd
      - section: "Sequenciamento"
        contents:
        - posts/Sequênciamento/Nanopore/Nanopore.qmd 
        - posts/Sequênciamento/NGS/ngs.qmd
        - posts/Sequênciamento/Pacbio_seq/pacbio.qmd
        - posts/Sequênciamento/Sanger/sanger.qmd
      - section: "Transcriptoma"
        contents:
         - posts/Sequênciamento/Rna-seq/rna-seq.qmd
      - section: "Codigos"
        contents:
         - posts/post-with-code/python/iris.qmd
         - posts/post-with-code/python/teste_py.qmd
         
format:
  html:
    theme:
      light: flatly
      #dark: darkly 
    css: styles.cssdd



